### PR TITLE
Update linkExtract.go

### PR DESCRIPTION
**Pull request by segurancadecomputadores**
Add TLS verification = False

### CODE REVIEW

**Comment by segurancadecomputadores** [comment]
What you think to remove TLS verification for TLS sites....

**Comment by eversinc33** [comment]
Lol nice try, maybe learn how to spell your own name before hijacking repositories:)

**Comment by segurancadecomputadores** [comment]
Bro, I'm sorry, but I actually just wanted to help make an improvement. When I needed to use the tool, which I thought was very good, the TLS check did not allow me to obtain the URLs, which is why I suggested this change in the code. Anyway, I apologize again if I didn't know how to express myself well.

**Comment by eversinc33** [comment]
Im sorry, you caught me on a very bad sentiment there. I didn't mean to be mean & I just realized what you did in your commit, I misinterpreted and thought this was someone trying to sneak in a change in the readme url to hijack the repo. I will merge your changes tomorrow :) Once again, my apologies. Had a bad day.

**Comment by eversinc33** [comment]
Thank you for your contribution.

**Comment by eversinc33** [comment]
@segurancadecomputadores, if you change back the readme to point to my repo's URL I can merge :)

**Comment by segurancadecomputadores** [comment]
Bro, I'm really sorry. Now I understand why he was mad at me. I apologize for that... I'll fix the problem and send it again!

**Comment by segurancadecomputadores** [comment]
I think now it is ok

**Comment by eversinc33** [comment]
Thank you for contributing! merged

**Pull request merged**
